stm32f7: ethernet: fix the 'bitwise comparison always evaluates to false' error
PX4/NuttX pull request #104
Opened 2020-05-28 15:25 UTC by TSC21

PX4 CI building with GCC 9 was complaining about an error regarding this bitwise comparison. It doesn't look good to me as we basically do a double negation, but like this it doesn't complain.

https://github.com/PX4/Firmware/pull/14691/checks?check_run_id=595172297#step:6:553

2020-05-28 15:53 UTC, davids5 requested changes
We will need a better solution. This type of code is everywhere

2020-05-28 15:54 UTC, TSC21 commented
> We will need a better solution. This type of code is everywhere

Any suggestion? We can try to embrace the bitwise operation in a different way.

2020-06-05 21:38 UTC, closed without merging

2020-06-05 21:38 UTC, davids5 commented
See https://github.com/PX4/Firmware/pull/15046

2020-06-05 21:38 UTC, TSC21 commented
Thanks!