S32K1XX FlexCAN fix & EEEPROM driver
PX4/NuttX pull request #107
Opened 2020-06-04 09:30 UTC by PetervdPerk-NXP

This PR includes contains some fixes for the FlexCAN driver:
- Bitrate calculation fix
- FlexCAN TX done and transmit race condition

Furthermore it includes the Enhanced EEPROM (4kb) block device driver which allows PX4 to store it's parameters on.

2020-06-04 09:59 UTC, TSC21 commented
@LorenzMeier FYI

2020-06-11 07:52 UTC, PetervdPerk-NXP commented
Any update on this PR? it's required to enable parameter storage for https://github.com/PX4/Firmware/pull/14865

2020-06-15 20:48 UTC, davids5 requested changes
@PetervdPerk-NXP are these changes already in upstream?  

We would need then to be up streamed and back ported or on the next upgradw we will loose the changes.

2020-06-15 20:48 UTC, davids5 commented on arch/arm/src/kinetis/kinetis_flexcan.c
> +  up_enable_irq(priv->config->mb_irq);
Why are these changes not enabling or disabling the the IRQ from the IP block?

2020-06-15 20:50 UTC, davids5 commented on arch/arm/src/kinetis/kinetis_flexcan.c
> +  up_enable_irq(priv->config->mb_irq);
> Any update on this PR? it's required to enable parameter storage for PX4/Firmware#14865

Sorry I had asked a question days ago but did not hit comment. So it was sitting here.

2020-06-16 06:26 UTC, PetervdPerk-NXP commented on arch/arm/src/kinetis/kinetis_flexcan.c
> +  up_enable_irq(priv->config->mb_irq);
I took over the idea from the Kinetis Enet driver (Which apparantly isn't ideal :wink:). But you're right I can also use the FlexCAN Interrupt Mask (IMASK1) register. Let me try & test using that register.

2020-06-16 23:10 UTC, davids5 commented on arch/arm/src/kinetis/kinetis_flexcan.c
> +  up_enable_irq(priv->config->mb_irq);
> I took over the idea from the Kinetis Enet driver

yep - I just fixed that!

2020-06-17 11:35 UTC, davids5 submitted a review, later dismissed
Thank you @PetervdPerk-NXP

2020-06-17 11:37 UTC, davids5 commented
@dagar do you want to test with PX4/Firmware#14865?

2020-06-17 15:29 UTC, PetervdPerk-NXP commented
I've tested it with https://github.com/PX4/Firmware/pull/14865 found a mistake in SocketCAN regarding timestamping. Latest commit fixes that, I will make a seperate PR to backport that change to upstream NuttX

2020-06-17 22:19 UTC, davids5 commented
@PetervdPerk-NXP - I just merged the upstream version of f76dc9a. Please add [BACKPORT] to the commit message and force push here.

2021-03-06 14:35 UTC, davids5 commented
Stale 10.0.0+ and backports has brought this in

2021-03-06 14:35 UTC, closed without merging